[target.aarch64-apple-darwin]
image = "aarch64-apple-darwin-cross"

[target.x86_64-apple-darwin]
image = "x86_64-apple-darwin-cross"

[target.aarch64-pc-windows-msvc]
image = "aarch64-pc-windows-msvc-cross"

[target.i686-pc-windows-msvc]
image = "i686-pc-windows-msvc-cross"

[target.x86_64-pc-windows-msvc]
image = "x86_64-pc-windows-msvc-cross"
