name: "Cross-platform Rust build"
description: "Build a Rust project for multiple platforms"

inputs:
  name:
    description: "Name of the binary to build"
    required: true
  target:
    description: Target triple to build for
    required: true
  cross-version:
    description: Version of cross to use
    required: true
    default: "0.2.5"

runs:
  using: "composite"

  steps:
    - run: |
        rustup update stable
        curl -sSfL https://github.com/cross-rs/cross/releases/download/v${{ inputs.cross-version }}/cross-x86_64-unknown-linux-musl.tar.gz | sudo tar xzf - -C /usr/local/bin
      shell: bash

    - uses: docker/setup-buildx-action@v3

    - run: git clone --depth 1 --branch v${{ inputs.cross-version }} --recursive https://github.com/cross-rs/cross /tmp/cross
      shell: bash
      if: contains(matrix.target, 'darwin') || contains(matrix.target, 'msvc')

    - uses: docker/build-push-action@v5
      with:
        context: /tmp/cross/docker
        file: /tmp/cross/docker/cross-toolchains/docker/Dockerfile.${{ matrix.target }}-cross
        build-args: |
          MACOS_SDK_URL=https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
        tags: "${{ matrix.target }}-cross:latest"
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
      if: contains(matrix.target, 'darwin') || contains(matrix.target, 'msvc')

    - run: |
        uppercase_target=$(echo "${{ matrix.target }}" | tr '-' '_' | tr '[:lower:]' '[:upper:]')
        export CROSS_TARGET_${uppercase_target}_IMAGE=${{ matrix.target }}-cross
        cross build --release --bin ${{ inputs.name }} --target ${{ matrix.target }}
      shell: bash

    - run: |
        tar czf ${{ inputs.name }}.${{ matrix.target }}.tar.gz \
          -C target/${{ matrix.target }}/release \
          ${{ inputs.name }}${{ contains(matrix.target, 'windows') && '.exe' || '' }}
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}.${{ matrix.target }}.tar.gz
        path: ${{ inputs.name }}.${{ matrix.target }}.tar.gz
        if-no-files-found: error

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ inputs.name }}.${{ matrix.target }}.tar.gz
        draft: true
