name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NAME: hello-world

    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - aarch64-pc-windows-msvc
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - i686-pc-windows-gnu
          - i686-pc-windows-msvc
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4

      - run: rustup update stable

      - run: curl -sSfL https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-musl.tar.gz | sudo tar xzf - -C /usr/local/bin

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - run: git clone --depth=1 --recursive https://github.com/cross-rs/cross
        if: contains(matrix.target, 'darwin') || contains(matrix.target, 'msvc')

      - uses: docker/build-push-action@v5
        with:
          context: cross/docker
          file: cross/docker/cross-toolchains/docker/Dockerfile.${{ matrix.target }}-cross
          build-args: |
            MACOS_SDK_URL=https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
          tags: "${{ matrix.target }}-cross:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
        if: contains(matrix.target, 'darwin') || contains(matrix.target, 'msvc')

      - run: cross build --release --target ${{ matrix.target }}

      - run: echo "FILENAME=$FILENAME" >> $GITHUB_ENV
        env:
          FILENAME: ${{ env.NAME }}${{ contains(matrix.target, 'windows') && '.exe' || '' }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ env.FILENAME }}

      - run: tar czf $NAME.${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release $FILENAME

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.NAME }}.${{ matrix.target }}.tar.gz
          draft: true
