name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - aarch64-pc-windows-msvc
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - i686-pc-windows-gnu
          - i686-pc-windows-msvc
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4

      - run: rustup update stable

      - run: curl -sSfL https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-musl.tar.gz | sudo tar xzf - -C /usr/local/bin

      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true
        if: contains(matrix.target, 'darwin') || contains(matrix.target, 'msvc')

      - run: git clone --depth=1 --recursive https://github.com/cross-rs/cross
        if: contains(matrix.target, 'darwin') || contains(matrix.target, 'msvc')

      - run: cross build --release --target ${{ matrix.target }}

      - run: echo "FILENAME=$FILENAME" >> $GITHUB_ENV
        env:
          FILENAME: hello-world${{ contains(matrix.target, 'windows') && '.exe' || '' }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAME }}
          path: target/${{ matrix.target }}/release/${{ env.FILENAME }}
