name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - aarch64-pc-windows-msvc
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - i686-pc-windows-gnu
          - i686-pc-windows-msvc
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        if: contains(matrix.target, 'apple')

      - run: git clone --depth 0 --recursive https://github.com/cross-rs/cross
        if: contains(matrix.target, 'apple')

      - run: cross build --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/hello-world
